# Generated by Django 4.1.1 on 2022-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptopname', models.CharField(max_length=40)),
                ('laptopcompany', models.CharField(max_length=50)),
                ('laptopram', models.CharField(max_length=30)),
                ('laptoprom', models.CharField(max_length=30)),
                ('laptopprice', models.CharField(max_length=30)),
                ('laptopprocessor', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
